### ISSUE TITLE
Release key after Drag function

### ISSUE THREAD

**Issue by derycck** [4strid/mouse-control.autohotkey#5]
I couldn't find a way to release the mouse button after using the drag function (press v). 
In the code I read a comment on line 422 informing that this could be implemented in the future. 

Is there an estimated date for this implementation?

obs: thanks for the scriipt. Help me a lot!

**Comment by 4strid** [comment]
i believe that pressing `v` again after beginning to drag cleanly releases the drag (or it did on one of my computers but may have never been pushed to github... ) please let me know if this is not the case as i no longer have access to a computer running windows . in the meanwhile , clicking again with `i` has the additional effect of releasing the drag , and works desirably in most cases .

**Comment by 4strid** [comment]
no worries & thanks for the code snippet I'll go ahead and fill in the gaps
and then push an update later today . saúde !

**Comment by 4strid** [comment]
this has been implemented as part of #8 , thanks for your help

sorry for the delay i was homeless for the past few years
