### ISSUE TITLE
Please add Hold Middle Mouse Button

### ISSUE THREAD

**Issue by barkoder** [4strid/mouse-control.autohotkey#8]
Please add a hold middle mouse button. I really need it for a [Window arrangement script](https://github.com/jgpaiva/GridMove) that I like to use. It also doesn't help that that MMB on every mouse is always the first to fail. For some reason, literally every single mouse manufacturer insists on using a subpar switch for the Scroll Wheel Button.

-----------------------------

Thank you for your work on this script, @4strid. Seriously.
When I was disabled and bedridden due to an injury, your script(along with a couple of android apps) helped me operate my computer while I lay in bed without me having to strain myself reaching for the mouse every time. I've recovered now, and your script still continues to help me avoid pain.

Sincerely, Thank you. So...so much.

I would give you money if I could but sadly I can't, so I hope you find these words somewhat comforting.

I wish you the very best. And may life be kind to you @4strid .

Thank you!

**Comment by 4strid** [comment]
no prob boss ; sorry about the delay . i was in rehab or i'd have gotten to you sooner .

life is getting a lot better now .  i've been homeless for a long time , or was I should say ; that period of my life is thankfully over . despite losing everything i owned save what i brought with me to rehab , i thank God every day for what i do have , including this windows computer to develop on . thank you for your kind words , they mean more than you'd know .

**Comment by 4strid** [comment]
ok give it a spin let me know if that works for you . I made middle click drag `c`  . I can change the binding too if it doesn't suit you
